/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static Vista.VFormaciones.CbxHorario;
import javax.swing.JFileChooser;

/**
 *
 * @author APRENDIZ
 */
public class VUsuario extends javax.swing.JFrame {



    /**
     * @return the CbxRol
     */
    public static javax.swing.JComboBox<String> getCbxRol() {
        return CbxRol;
    }

    /**
     * @param aCbxRol the CbxRol to set
     */
    public static void setCbxRol(javax.swing.JComboBox<String> aCbxRol) {
        CbxRol = aCbxRol;
    }

    /**
     * @return the TblUsua
     */
    public static javax.swing.JTable getTblUsua() {
        return TblUsua;
    }

    /**
     * @param aTblUsua the TblUsua to set
     */
    public static void setTblUsua(javax.swing.JTable aTblUsua) {
        TblUsua = aTblUsua;
    }

    /**
     * @return the TxtApellido
     */
    public static javax.swing.JTextField getTxtApellido() {
        return TxtApellido;
    }

    /**
     * @param aTxtApellido the TxtApellido to set
     */
    public static void setTxtApellido(javax.swing.JTextField aTxtApellido) {
        TxtApellido = aTxtApellido;
    }

    /**
     * @return the TxtCelular
     */
    public static javax.swing.JTextField getTxtCelular() {
        return TxtCelular;
    }

    /**
     * @param aTxtCelular the TxtCelular to set
     */
    public static void setTxtCelular(javax.swing.JTextField aTxtCelular) {
        TxtCelular = aTxtCelular;
    }

    /**
     * @return the TxtCorreo
     */
    public static javax.swing.JTextField getTxtCorreo() {
        return TxtCorreo;
    }

    /**
     * @param aTxtCorreo the TxtCorreo to set
     */
    public static void setTxtCorreo(javax.swing.JTextField aTxtCorreo) {
        TxtCorreo = aTxtCorreo;
    }

    /**
     * @return the TxtNombre
     */
    public static javax.swing.JTextField getTxtNombre() {
        return TxtNombre;
    }

    /**
     * @param aTxtNombre the TxtNombre to set
     */
    public static void setTxtNombre(javax.swing.JTextField aTxtNombre) {
        TxtNombre = aTxtNombre;
    }

    /**
     * @return the TxtUsu
     */
    public static javax.swing.JTextField getTxtUsu() {
        return TxtUsu;
    }

    /**
     * @param aTxtUsu the TxtUsu to set
     */
    public static void setTxtUsu(javax.swing.JTextField aTxtUsu) {
        TxtUsu = aTxtUsu;
    }

    /**
     * @return the TxtFormacion
     */
    public static javax.swing.JTextField getTxtFormacion() {
        return TxtFormacion;
    }

    /**
     * @param aTxtFormacion the TxtFormacion to set
     */
    public static void setTxtFormacion(javax.swing.JTextField aTxtFormacion) {
        TxtFormacion = aTxtFormacion;
    }

    /**
     * Creates new form VUsuario
     */
    public VUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnAlmaMac = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnElimUsuFic = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtUsu = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtApellido = new javax.swing.JTextField();
        TxtCelular = new javax.swing.JTextField();
        TxtCorreo = new javax.swing.JTextField();
        CbxRol = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblUsua = new javax.swing.JTable();
        BtnElimUsuInd = new javax.swing.JButton();
        TxtFormacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BtnAlmaMac.setText("Almacenamiento Macivo");
        BtnAlmaMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlmaMacActionPerformed(evt);
            }
        });

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnEditar.setText("Editar Usuario");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnElimUsuFic.setText("Eliminar Usuarios por Ficha");
        BtnElimUsuFic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnElimUsuFicActionPerformed(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("USUARIOS");

        jLabel2.setText("*campos obligatorios");

        jLabel3.setText("Documento*:");

        jLabel4.setText("Nombres*:");

        jLabel5.setText("Apellidos*:");

        jLabel6.setText("Celular*:");

        jLabel7.setText("E-mail*:");

        jLabel8.setText("Rol*:");

        jLabel9.setText("Ficha*:");

        CbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));

        TblUsua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Documento", "Nombres", "Apellidos", "Celular", "E-mail", "Rol", "Ficha"
            }
        ));
        TblUsua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblUsuaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblUsua);

        BtnElimUsuInd.setText("Eliminar Usuario Individual");
        BtnElimUsuInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnElimUsuIndActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtUsu)
                                    .addComponent(TxtNombre)
                                    .addComponent(TxtApellido)
                                    .addComponent(TxtCelular)
                                    .addComponent(TxtCorreo)
                                    .addComponent(CbxRol, 0, 155, Short.MAX_VALUE)
                                    .addComponent(TxtFormacion))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnAlmaMac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnElimUsuFic, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(BtnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnElimUsuInd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(CbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TxtFormacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnAlmaMac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnActualizar)
                        .addGap(5, 5, 5)
                        .addComponent(BtnElimUsuFic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnElimUsuInd)
                        .addGap(4, 4, 4)
                        .addComponent(BtnBuscar)))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAlmaMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlmaMacActionPerformed
        JFileChooser chooser = new JFileChooser();
        int opcion = chooser.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            
            String ruta_archivo = chooser.getSelectedFile().toString(); 
            
            Logica.LUsuario excel = new Logica.LUsuario();
            excel.registrarUsuarios(ruta_archivo);
        }
        
    }//GEN-LAST:event_BtnAlmaMacActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        
        String rol = ""+getCbxRol().getSelectedIndex();

        Datos.DUsuarios.registrarUsuarios(getTxtUsu().getText(), getTxtNombre().getText(), getTxtApellido().getText(), getTxtCelular().getText(), getTxtCorreo().getText(), rol, getTxtFormacion().getText());
        TxtUsu.setText("");
        TxtNombre.setText("");
        TxtApellido.setText("");
        TxtCelular.setText("");
        TxtCorreo.setText("");
        TxtFormacion.setText("");
        CbxRol.setSelectedIndex(0);

       
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        Datos.DUsuarios.buscarRol();
        Logica.LUsuario.buscarFormacion(TxtUsu.getText());
    }//GEN-LAST:event_formWindowOpened

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        
        String rol = ""+CbxRol.getSelectedIndex();

        Datos.DUsuarios.modificarUsuario(TxtUsu.getText(), TxtNombre.getText(), TxtApellido.getText(), TxtCelular.getText(),TxtCorreo.getText(), rol, TxtFormacion.getText());
        TxtUsu.setText("");
        TxtNombre.setText("");
        TxtApellido.setText("");
        TxtCelular.setText("");
        TxtCorreo.setText("");
        TxtFormacion.setText("");
        CbxRol.setSelectedIndex(0);

    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnElimUsuFicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnElimUsuFicActionPerformed
        
        //String ficha = ""+CbxFicha.getSelectedIndex();
        Datos.DUsuarios.eliminarAprendicesFicha(TxtFormacion.getText());
        TxtUsu.setText("");
        TxtNombre.setText("");
        TxtApellido.setText("");
        TxtCelular.setText("");
        TxtCorreo.setText("");
        TxtFormacion.setText("");
        CbxRol.setSelectedIndex(0);

    }//GEN-LAST:event_BtnElimUsuFicActionPerformed

    private void BtnElimUsuIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnElimUsuIndActionPerformed
        
        Datos.DUsuarios.eliminarAdministrativo(TxtUsu.getText());
        TxtUsu.setText("");
        TxtNombre.setText("");
        TxtApellido.setText("");
        TxtCelular.setText("");
        TxtCorreo.setText("");
        TxtFormacion.setText("");
        CbxRol.setSelectedIndex(0);

    }//GEN-LAST:event_BtnElimUsuIndActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        
        Logica.LUsuario.buscarFormacion(TxtUsu.getText());
        TxtUsu.setText("");
        TxtNombre.setText("");
        TxtApellido.setText("");
        TxtCelular.setText("");
        TxtCorreo.setText("");
        TxtFormacion.setText("");
        CbxRol.setSelectedIndex(0);

    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        
        TxtUsu.setText("");
        TxtNombre.setText("");
        TxtApellido.setText("");
        TxtCelular.setText("");
        TxtCorreo.setText("");
        TxtFormacion.setText("");
        CbxRol.setSelectedIndex(0);

        Logica.LUsuario.buscarFormacion(TxtUsu.getText());        
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void TblUsuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblUsuaMouseClicked
        
        Logica.LUsuario.llenarCapmos();
    }//GEN-LAST:event_TblUsuaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnAlmaMac;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnElimUsuFic;
    private javax.swing.JButton BtnElimUsuInd;
    private javax.swing.JButton BtnGuardar;
    public static javax.swing.JComboBox<String> CbxRol;
    public static javax.swing.JTable TblUsua;
    public static javax.swing.JTextField TxtApellido;
    public static javax.swing.JTextField TxtCelular;
    public static javax.swing.JTextField TxtCorreo;
    public static javax.swing.JTextField TxtFormacion;
    public static javax.swing.JTextField TxtNombre;
    public static javax.swing.JTextField TxtUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
